In [1]:
%load_ext autoreload

In [2]:
import os
os.chdir("..")

In [3]:
%autoreload 2
import pandas as pd
import numpy as np
%aimport AD_comparison_tools
%aimport AD_predictor_tools
%aimport ADpred_LambertTFs_helper
import protfasta

In [4]:
yeast_TFs = pd.read_csv("../output/yeast_TF_seqs.csv", index_col = 0)
yeast_TFs = yeast_TFs.rename(columns = {"seq" : "sequence"})
yeast_TFs["uniprotID"] = yeast_TFs["id"].str.split("|").str[1]
yeast_TFs = yeast_TFs.drop(columns = "id")
yeast_TFs

                                              sequence uniprotID
0    MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...    O14467
1    MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...    O93958
2    MSEYQPSLFALNPMGFSPLDGSKSTNENVSASTSTAKPMVGQLIFD...    P03069
3    MKLLSSIEQACDICRLKKLKCSKEKPKCAKCLKNNWECRYSPKTKR...    P04386
4    MDYNKRSSVSTVPNAAPIRVGFVGLNAAKGWAIKTHYPAILQLSSQ...    P04387
..                                                 ...       ...
242  MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...    Q707Y3
243  MQFTILNEPSLDSQRREGDLASENYVFGDIRKEGVRILEDSLRSER...    Q707Y6
244  MNVQEIHNIREACITILSGTKHNSVLFEPCDKFDEVINSLDIDPDS...    Q708A1
245  MCDNDMADIQSKLSSFCEEIRALALKEGYNLEGDKSPSSKPYFMSW...    Q9HG12
246  MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...    Q9HG13

[247 rows x 2 columns]

In [5]:
preds = pd.read_csv("../output/yeast_TFs_preds/tada/yeast_TF/tada_preds.csv", index_col = 0)
preds

,sequence,tada_centers,tada_preds
0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.17324699461460114, 0.1775343120098114, 0.17..."
1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.2978363335132599, 0.2630658447742462, 0.248..."
2,MSEYQPSLFALNPMGFSPLDGSKSTNENVSASTSTAKPMVGQLIFD...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.24354827404022217, 0.22880962491035461, 0.2..."
3,MKLLSSIEQACDICRLKKLKCSKEKPKCAKCLKNNWECRYSPKTKR...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.15083006024360657, 0.1525242179632187, 0.14..."
4,MDYNKRSSVSTVPNAAPIRVGFVGLNAAKGWAIKTHYPAILQLSSQ...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16490736603736877, 0.1633058786392212, 0.15..."
...,...,...,...
242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16285842657089233, 0.15215648710727692, 0.1..."
243,MQFTILNEPSLDSQRREGDLASENYVFGDIRKEGVRILEDSLRSER...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21525731682777405, 0.23573869466781616, 0.2..."
244,MNVQEIHNIREACITILSGTKHNSVLFEPCDKFDEVINSLDIDPDS...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.25385382771492004, 0.28984490036964417, 0.3..."
245,MCDNDMADIQSKLSSFCEEIRALALKEGYNLEGDKSPSSKPYFMSW...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.23435993492603302, 0.21959690749645233, 0.2..."
246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21394184231758118, 0.1734418272972107, 0.17..."

In [6]:
preds = pd.merge(yeast_TFs, preds, on = "sequence").drop_duplicates().reset_index(drop = True)
preds

,sequence,uniprotID,tada_centers,tada_preds
0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.17324699461460114, 0.1775343120098114, 0.17..."
1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.2978363335132599, 0.2630658447742462, 0.248..."
2,MSEYQPSLFALNPMGFSPLDGSKSTNENVSASTSTAKPMVGQLIFD...,P03069,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.24354827404022217, 0.22880962491035461, 0.2..."
3,MKLLSSIEQACDICRLKKLKCSKEKPKCAKCLKNNWECRYSPKTKR...,P04386,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.15083006024360657, 0.1525242179632187, 0.14..."
4,MDYNKRSSVSTVPNAAPIRVGFVGLNAAKGWAIKTHYPAILQLSSQ...,P04387,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16490736603736877, 0.1633058786392212, 0.15..."
...,...,...,...,...
242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16285842657089233, 0.15215648710727692, 0.1..."
243,MQFTILNEPSLDSQRREGDLASENYVFGDIRKEGVRILEDSLRSER...,Q707Y6,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21525731682777405, 0.23573869466781616, 0.2..."
244,MNVQEIHNIREACITILSGTKHNSVLFEPCDKFDEVINSLDIDPDS...,Q708A1,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.25385382771492004, 0.28984490036964417, 0.3..."
245,MCDNDMADIQSKLSSFCEEIRALALKEGYNLEGDKSPSSKPYFMSW...,Q9HG12,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.23435993492603302, 0.21959690749645233, 0.2..."
246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21394184231758118, 0.1734418272972107, 0.17..."

In [7]:
def activity_string_to_array(prob_string):
    a = prob_string.replace('\n','')
    a = a.replace('[','')
    a = a.replace(']','').split(",")
    b = []
    for x in a:
        if x != "":
            b.append(float(x))
    return b

float_preds = []

for str_list in preds["tada_preds"]:
    float_preds.append(activity_string_to_array(str_list))
    
preds["tada_preds"] = float_preds
preds

,sequence,uniprotID,tada_centers,tada_preds
0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.17324699461460114, 0.1775343120098114, 0.17..."
1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.2978363335132599, 0.2630658447742462, 0.248..."
2,MSEYQPSLFALNPMGFSPLDGSKSTNENVSASTSTAKPMVGQLIFD...,P03069,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.24354827404022217, 0.22880962491035461, 0.2..."
3,MKLLSSIEQACDICRLKKLKCSKEKPKCAKCLKNNWECRYSPKTKR...,P04386,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.15083006024360657, 0.1525242179632187, 0.14..."
4,MDYNKRSSVSTVPNAAPIRVGFVGLNAAKGWAIKTHYPAILQLSSQ...,P04387,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16490736603736877, 0.1633058786392212, 0.15..."
...,...,...,...,...
242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16285842657089233, 0.15215648710727692, 0.1..."
243,MQFTILNEPSLDSQRREGDLASENYVFGDIRKEGVRILEDSLRSER...,Q707Y6,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21525731682777405, 0.23573869466781616, 0.2..."
244,MNVQEIHNIREACITILSGTKHNSVLFEPCDKFDEVINSLDIDPDS...,Q708A1,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.25385382771492004, 0.28984490036964417, 0.3..."
245,MCDNDMADIQSKLSSFCEEIRALALKEGYNLEGDKSPSSKPYFMSW...,Q9HG12,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.23435993492603302, 0.21959690749645233, 0.2..."
246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21394184231758118, 0.1734418272972107, 0.17..."

In [8]:
float_centers = []

for str_list in preds["tada_centers"]:
    float_centers.append(activity_string_to_array(str_list))
    
preds["tada_centers"] = float_centers
preds

,sequence,uniprotID,tada_centers,tada_preds
0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.17324699461460114, 0.1775343120098114, 0.17..."
1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.2978363335132599, 0.2630658447742462, 0.248..."
2,MSEYQPSLFALNPMGFSPLDGSKSTNENVSASTSTAKPMVGQLIFD...,P03069,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.24354827404022217, 0.22880962491035461, 0.2..."
3,MKLLSSIEQACDICRLKKLKCSKEKPKCAKCLKNNWECRYSPKTKR...,P04386,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.15083006024360657, 0.1525242179632187, 0.14..."
4,MDYNKRSSVSTVPNAAPIRVGFVGLNAAKGWAIKTHYPAILQLSSQ...,P04387,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16490736603736877, 0.1633058786392212, 0.15..."
...,...,...,...,...
242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.16285842657089233, 0.15215648710727692, 0.1..."
243,MQFTILNEPSLDSQRREGDLASENYVFGDIRKEGVRILEDSLRSER...,Q707Y6,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21525731682777405, 0.23573869466781616, 0.2..."
244,MNVQEIHNIREACITILSGTKHNSVLFEPCDKFDEVINSLDIDPDS...,Q708A1,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.25385382771492004, 0.28984490036964417, 0.3..."
245,MCDNDMADIQSKLSSFCEEIRALALKEGYNLEGDKSPSSKPYFMSW...,Q9HG12,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.23435993492603302, 0.21959690749645233, 0.2..."
246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.21394184231758118, 0.1734418272972107, 0.17..."

In [9]:
preds_expanded = preds.explode(['tada_centers', 'tada_preds']).reset_index()
preds_expanded

,index,sequence,uniprotID,tada_centers,tada_preds
0,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,20.0,0.173247
1,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,21.0,0.177534
2,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,22.0,0.171363
3,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,23.0,0.163574
4,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,24.0,0.162611
...,...,...,...,...,...
138905,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,233.0,0.15929
138906,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,234.0,0.171703
138907,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,235.0,0.201173
138908,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,236.0,0.233172
138909,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,237.0,0.262142

In [11]:
tiles = []
starts = []
ends = []

for i in preds_expanded.index:
    full_seq = preds_expanded["sequence"].iloc[i]
    center = int(preds_expanded["tada_centers"].iloc[i])
    
    start = center - 20
    end = center + 20
    tile = full_seq[start : end]
    
    starts.append(start)
    ends.append(end)
    tiles.append(tile)

preds_expanded["tile"] = tiles
preds_expanded["start"] = starts
preds_expanded["end"] = ends
preds_expanded

,index,sequence,uniprotID,tada_centers,tada_preds,tile,start,end
0,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,20.0,0.173247,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGL,0,40
1,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,21.0,0.177534,SDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLV,1,41
2,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,22.0,0.171363,DWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVV,2,42
3,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,23.0,0.163574,WDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVS,3,43
4,0,MSDWDTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSVDK...,O14467,24.0,0.162611,DTNTIIGSRARAGGSGPRANVARSQGQINAARRQGLVVSV,4,44
...,...,...,...,...,...,...,...,...
138905,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,233.0,0.15929,KMNSNLSKLRFKSKQPPTPPEENSNVFKKRYTSENRIIED,213,253
138906,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,234.0,0.171703,MNSNLSKLRFKSKQPPTPPEENSNVFKKRYTSENRIIEDL,214,254
138907,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,235.0,0.201173,NSNLSKLRFKSKQPPTPPEENSNVFKKRYTSENRIIEDLF,215,255
138908,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,236.0,0.233172,SNLSKLRFKSKQPPTPPEENSNVFKKRYTSENRIIEDLFL,216,256
138909,246,MANSTLRRTTFFKLTTTEDEDTIPKLLQPNNNSVAFPNLKRTGKAF...,Q9HG13,237.0,0.262142,NLSKLRFKSKQPPTPPEENSNVFKKRYTSENRIIEDLFLM,217,257

In [13]:
active_preds = preds_expanded[preds_expanded["tada_preds"] > 0.5]
active_preds

,index,sequence,uniprotID,tada_centers,tada_preds,tile,start,end
304,1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,212.0,0.525377,MTVSPMTAFFSNNSHVTCYDPNFVLDTPTREFLMMPLDDI,192,232
305,1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,213.0,0.534587,TVSPMTAFFSNNSHVTCYDPNFVLDTPTREFLMMPLDDIT,193,233
306,1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,214.0,0.54636,VSPMTAFFSNNSHVTCYDPNFVLDTPTREFLMMPLDDITL,194,234
307,1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,215.0,0.552861,SPMTAFFSNNSHVTCYDPNFVLDTPTREFLMMPLDDITLP,195,235
308,1,MENTILHIHSFQLPQTEQPYPEAMLFDRDTSDSRTVLTQKPNGLEI...,O93958,216.0,0.532153,PMTAFFSNNSHVTCYDPNFVLDTPTREFLMMPLDDITLPS,196,236
...,...,...,...,...,...,...,...,...
138170,242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,49.0,0.563399,HEQSIEISSSLKWFEEISEWMSKFPESGLYISTTIWTFLE,29,69
138171,242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,50.0,0.571711,EQSIEISSSLKWFEEISEWMSKFPESGLYISTTIWTFLEG,30,70
138172,242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,51.0,0.560527,QSIEISSSLKWFEEISEWMSKFPESGLYISTTIWTFLEGV,31,71
138173,242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,52.0,0.531968,SIEISSSLKWFEEISEWMSKFPESGLYISTTIWTFLEGVP,32,72
138174,242,MPSRTPTDIWRCQRLILAARKGETTCQALHEQSIEISSSLKWFEEI...,Q707Y3,53.0,0.511091,IEISSSLKWFEEISEWMSKFPESGLYISTTIWTFLEGVPN,33,73

In [15]:
active_tile_coords = active_preds[["uniprotID", "start", "end"]]
active_tile_coords = active_tile_coords.rename(columns = {"start" : "Start", "end" : "End"})
active_tile_coords

       uniprotID  Start  End
304       O93958    192  232
305       O93958    193  233
306       O93958    194  234
307       O93958    195  235
308       O93958    196  236
...          ...    ...  ...
138170    Q707Y3     29   69
138171    Q707Y3     30   70
138172    Q707Y3     31   71
138173    Q707Y3     32   72
138174    Q707Y3     33   73

[4301 rows x 3 columns]

In [16]:
# From preparing TADA preds

def return_merged_row(uniprotID, df):
    # Only look at rows with the same uniprot ID
    same_uniprotID_rows = df[df["uniprotID"] == uniprotID]
    same_uniprotID_rows = same_uniprotID_rows.sort_values(by = "Start")
    
    # Final dataframe columns
    new_starts = []
    new_ends = []
    orig_uniprotIDs = []
    
    # Current row's values
    curr_start = -1
    curr_end = -1
    curr_orig_uniprotIDs = []
    
    for i in same_uniprotID_rows.index:
        # Merge current row with next row
        if curr_end >= same_uniprotID_rows.loc[i]["Start"]:
            curr_end = max(curr_end, same_uniprotID_rows.loc[i]["End"])
        
        # Don't merge current row with next row
        else: 
            new_starts.append(curr_start)
            new_ends.append(curr_end)

            curr_orig_uniprotIDs = [str(c) for c in curr_orig_uniprotIDs]            
            
            curr_start = same_uniprotID_rows.loc[i]["Start"]
            curr_end = same_uniprotID_rows.loc[i]["End"]
    
    # Append the last values
    new_starts.append(curr_start)
    new_ends.append(curr_end)
    
    

    # curr_matching_isoforms = [c for c in curr_matching_isoforms]
    curr_orig_uniprotIDs = [str(c) for c in curr_orig_uniprotIDs]
    orig_uniprotIDs.append(" / ".join(curr_orig_uniprotIDs))
    
    # Remove the first (because it is just -1 or "")
    new_starts = new_starts[1:]
    new_ends = new_ends[1:]
    orig_uniprotIDs = orig_uniprotIDs[1:]
    
    return pd.DataFrame({"uniprotID" :uniprotID,
                         "Start": new_starts,
                        "End": new_ends
                        })

In [17]:
active_tile_coords.reset_index(inplace= True,drop=True)

dfs = []
i = 0
for uniprotID in active_tile_coords["uniprotID"].unique():
    dfs.append(return_merged_row(uniprotID, active_tile_coords))

merged_active_tile_coords = pd.concat(dfs)
merged_active_tile_coords = merged_active_tile_coords.reset_index(drop = True)
merged_active_tile_coords

    uniprotID  Start  End
0      O93958    192  290
1      P03069     40  149
2      P04386    135  207
3      P04386    830  880
4      P04387    364  410
..        ...    ...  ...
291    Q12363     49   94
292    Q12457    129  180
293    Q12753    272  337
294    Q12753    651  694
295    Q707Y3     11   73

[296 rows x 3 columns]

In [18]:
merged_active_tile_coords.to_csv("../output/yeast_TFs_preds/cleaned/tada.csv")